--ALTER DATABASE socialnetwork SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

-- CREATE DATABASE socialnetwork
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     CONNECTION LIMIT = -1
--     IS_TEMPLATE = False;

DROP TABLE IF EXISTS friendships;  
DROP TABLE IF EXISTS users;  

CREATE TABLE users (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	first_name CHARACTER VARYING(50),
	last_name CHARACTER VARYING(50)
);

CREATE TABLE friendships (
	id1 BIGINT,
	id2 BIGINT CHECK (id1 < id2),
	CONSTRAINT fk_id1
      FOREIGN KEY(id1) 
	  REFERENCES users(id),
	CONSTRAINT fk_id2
      FOREIGN KEY(id2) 
	  REFERENCES users(id),
	PRIMARY KEY (id1, id2)
);

